import { Referent, Referral } from './types';

const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

export const seedReferents: Referent[] = [
  {
    id: 'r1',
    name: 'Red Rock Recovery Ranch',
    organization: 'Red Rock Behavioral Group',
    type: 'Residential / Inpatient',
    city: 'St. George',
    state: 'UT',
    phone: '435-555-0142',
    email: 'admissions@redrockranch.example',
    cashPrice: 32000,
    priceUnit: '/month',
    insurance: ['Aetna', 'Cigna', 'UnitedHealthcare', 'SelectHealth', 'Out-of-Network'],
    specialties: ['Trauma', 'Dual Diagnosis', 'Equine Therapy', 'Experiential / Adventure', 'EMDR', '12-Step Integration'],
    notes: '45-90 day program. Strong equine program, great with resistant young adult males. Admissions dir: Kelly.',
    createdAt: daysAgo(400),
  },
  {
    id: 'r2',
    name: 'Harbor Point Detox',
    type: 'Detox',
    city: 'Scottsdale',
    state: 'AZ',
    phone: '480-555-0177',
    email: 'intake@harborpointdetox.example',
    cashPrice: 2500,
    priceUnit: '/day',
    insurance: ['Aetna', 'Blue Cross Blue Shield of Arizona', 'Cigna', 'Humana', 'UnitedHealthcare'],
    specialties: ['MAT', 'Dual Diagnosis'],
    notes: 'Medical detox, 24/7 admits. Will pick up from airport. Fast VOB turnaround.',
    createdAt: daysAgo(380),
  },
  {
    id: 'r3',
    name: 'Dr. Sarah Whitfield, LMFT',
    organization: 'Whitfield Family Therapy',
    type: 'Therapist',
    city: 'Denver',
    state: 'CO',
    phone: '303-555-0129',
    email: 'sarah@whitfieldtherapy.example',
    cashPrice: 225,
    priceUnit: '/session',
    insurance: ['Out-of-Network'],
    specialties: ['IFS', 'Trauma', 'Family Systems', 'EMDR'],
    notes: 'Excellent for family work post-intervention. 2-3 week waitlist typically.',
    createdAt: daysAgo(300),
  },
  {
    id: 'r4',
    name: 'Summit Trail IOP',
    organization: 'Summit Trail Health',
    type: 'IOP',
    city: 'Salt Lake City',
    state: 'UT',
    phone: '801-555-0163',
    email: 'referrals@summittrail.example',
    cashPrice: 7500,
    priceUnit: '/month',
    insurance: ['Aetna', 'SelectHealth', 'Regence BCBS of Utah', 'Cigna', 'Optum', 'UnitedHealthcare', 'Utah Medicaid'],
    specialties: ['CBT', 'DBT', 'Dual Diagnosis', 'Young Adults'],
    notes: 'Day + evening tracks. Good step-down partner from Red Rock.',
    createdAt: daysAgo(350),
  },
  {
    id: 'r5',
    name: 'Mesa Verde PHP',
    organization: 'Mesa Verde Behavioral',
    type: 'PHP',
    city: 'Phoenix',
    state: 'AZ',
    phone: '602-555-0114',
    email: 'admissions@mesaverdebh.example',
    cashPrice: 14000,
    priceUnit: '/month',
    insurance: ['Blue Cross Blue Shield of Arizona', 'Banner Health Plans', 'Cigna', 'Magellan'],
    specialties: ['Dual Diagnosis', 'Trauma', 'DBT', 'Eating Disorders'],
    notes: 'Housing available. Strong psychiatry coverage, handles complex med cases.',
    createdAt: daysAgo(280),
  },
  {
    id: 'r6',
    name: 'Jake Morrison, CIP',
    organization: 'Turning Point Interventions',
    type: 'Interventionist',
    city: 'Nashville',
    state: 'TN',
    phone: '615-555-0186',
    email: 'jake@turningpointtn.example',
    cashPrice: 7500,
    priceUnit: '/case',
    insurance: [],
    specialties: ['Family Systems', '12-Step Integration', 'Chronic Relapse'],
    notes: 'Covers Southeast. Refers West-coast cases to us; we send Southeast cases to him.',
    createdAt: daysAgo(500),
  },
  {
    id: 'r7',
    name: 'Stillwater Ranch',
    organization: 'Stillwater Programs',
    type: 'Residential / Inpatient',
    city: 'Bozeman',
    state: 'MT',
    phone: '406-555-0155',
    email: 'admit@stillwaterranch.example',
    cashPrice: 45000,
    priceUnit: '/month',
    insurance: ['Out-of-Network'],
    specialties: ['Equine Therapy', 'Experiential / Adventure', 'Trauma', 'Somatic Experiencing', 'Young Adults'],
    notes: 'Premium wilderness-adjacent program. Cash-pay families only, superb outcomes with trauma.',
    createdAt: daysAgo(320),
  },
  {
    id: 'r8',
    name: 'Coastal Bridge IOP',
    organization: 'Coastal Bridge Health',
    type: 'IOP',
    city: 'Newport Beach',
    state: 'CA',
    phone: '949-555-0138',
    email: 'intake@coastalbridge.example',
    cashPrice: 9000,
    priceUnit: '/month',
    insurance: ['Aetna', 'Anthem Blue Cross of California', 'Cigna', 'Kaiser Permanente', 'Optum'],
    specialties: ['CBT', 'EMDR', 'Dual Diagnosis', 'Process Addictions', 'LGBTQ+ Affirming'],
    notes: 'Strong alumni program. Sends us 1-2 intervention cases per quarter.',
    createdAt: daysAgo(410),
  },
  {
    id: 'r9',
    name: 'Haven House Sober Living',
    type: 'Sober Living',
    city: 'Austin',
    state: 'TX',
    phone: '512-555-0171',
    email: 'manager@havenhouseatx.example',
    cashPrice: 1800,
    priceUnit: '/month',
    insurance: [],
    specialties: ['12-Step Integration', 'Young Adults'],
    notes: 'Structured men’s houses, drug testing, house managers on site. 90-day minimum.',
    createdAt: daysAgo(250),
  },
  {
    id: 'r10',
    name: 'Dr. Elena Vasquez, MD',
    organization: 'Vasquez Psychiatry',
    type: 'Psychiatrist',
    city: 'Dallas',
    state: 'TX',
    phone: '214-555-0122',
    email: 'office@vasquezpsych.example',
    cashPrice: 400,
    priceUnit: '/session',
    insurance: ['Aetna', 'Blue Cross Blue Shield of Texas', 'UnitedHealthcare'],
    specialties: ['Dual Diagnosis', 'MAT'],
    notes: 'Addiction psychiatry, telehealth in 12 states. Great for med management post-discharge.',
    createdAt: daysAgo(200),
  },
  {
    id: 'r11',
    name: 'Pine Creek Adolescent Center',
    organization: 'Pine Creek Health',
    type: 'Residential / Inpatient',
    city: 'Asheville',
    state: 'NC',
    phone: '828-555-0148',
    email: 'admissions@pinecreekteen.example',
    cashPrice: 28000,
    priceUnit: '/month',
    insurance: ['Aetna', 'Blue Cross NC', 'Cigna', 'Magellan', 'TRICARE'],
    specialties: ['Adolescents', 'Trauma', 'DBT', 'Family Systems', 'Eating Disorders'],
    notes: 'Ages 13-17. Academic program on site. Family weekends monthly.',
    createdAt: daysAgo(180),
  },
  {
    id: 'r12',
    name: 'Lighthouse Faith Recovery',
    type: 'Residential / Inpatient',
    city: 'Franklin',
    state: 'TN',
    phone: '615-555-0192',
    email: 'hope@lighthousefaith.example',
    cashPrice: 12000,
    priceUnit: '/month',
    insurance: ['TennCare', 'Medicare', 'BlueCross BlueShield of Tennessee'],
    specialties: ['Faith-Based', '12-Step Integration', 'Chronic Relapse'],
    notes: 'Affordable option, scholarship beds available. 6-month program.',
    createdAt: daysAgo(150),
  },
  {
    id: 'r13',
    name: 'Maria Chen, LCSW',
    type: 'Therapist',
    city: 'San Diego',
    state: 'CA',
    phone: '619-555-0107',
    email: 'maria@chentherapy.example',
    cashPrice: 190,
    priceUnit: '/session',
    insurance: ['Aetna', 'Kaiser Permanente', 'Optum'],
    specialties: ['DBT', 'CBT', 'Somatic Experiencing', 'LGBTQ+ Affirming', 'Young Adults'],
    notes: 'Refers family members needing intervention support. Quick to respond.',
    createdAt: daysAgo(120),
  },
  {
    id: 'r14',
    name: 'Crossroads Recovery Coaching',
    type: 'Recovery Coach',
    city: 'Boise',
    state: 'ID',
    phone: '208-555-0133',
    email: 'team@crossroadscoaching.example',
    cashPrice: 3500,
    priceUnit: '/month',
    insurance: [],
    specialties: ['Chronic Relapse', '12-Step Integration', 'Young Adults'],
    notes: 'Sober companions + transport. Reliable for case management between levels of care.',
    createdAt: daysAgo(100),
  },
];

export const seedReferrals: Referral[] = [
  { id: 'f1', referentId: 'r8', direction: 'inbound', clientLabel: 'J.T.', date: daysAgo(12), note: 'Family of alum, needs intervention for father' },
  { id: 'f2', referentId: 'r8', direction: 'inbound', clientLabel: 'M.R.', date: daysAgo(48), note: 'Alum relapse, family called' },
  { id: 'f3', referentId: 'r8', direction: 'inbound', clientLabel: 'D.W.', date: daysAgo(95) },
  { id: 'f4', referentId: 'r1', direction: 'outbound', clientLabel: 'K.S.', date: daysAgo(20), note: 'Post-intervention placement, 60-day' },
  { id: 'f5', referentId: 'r1', direction: 'inbound', clientLabel: 'B.H.', date: daysAgo(70), note: 'They needed an interventionist for an admit' },
  { id: 'f6', referentId: 'r2', direction: 'outbound', clientLabel: 'K.S.', date: daysAgo(23), note: 'Detox before Red Rock admit' },
  { id: 'f7', referentId: 'r6', direction: 'inbound', clientLabel: 'A.P.', date: daysAgo(30), note: 'West-coast case, referred to us' },
  { id: 'f8', referentId: 'r6', direction: 'inbound', clientLabel: 'C.L.', date: daysAgo(85), note: 'Utah family, out of his territory' },
  { id: 'f9', referentId: 'r6', direction: 'outbound', clientLabel: 'T.G.', date: daysAgo(60), note: 'Atlanta case, his territory' },
  { id: 'f10', referentId: 'r13', direction: 'inbound', clientLabel: 'R.N.', date: daysAgo(40), note: 'Client’s brother needs placement' },
  { id: 'f11', referentId: 'r4', direction: 'outbound', clientLabel: 'M.R.', date: daysAgo(38), note: 'Step-down after residential' },
  { id: 'f12', referentId: 'r7', direction: 'outbound', clientLabel: 'A.P.', date: daysAgo(25), note: 'Cash family, trauma focus' },
  { id: 'f13', referentId: 'r10', direction: 'inbound', clientLabel: 'S.B.', date: daysAgo(55), note: 'Patient needs structured placement' },
  { id: 'f14', referentId: 'r5', direction: 'outbound', clientLabel: 'S.B.', date: daysAgo(50) },
];
